version: '3.3'
services:
      
  db:
    image: mysql
    restart: always       
    environment:
      MYSQL_DATABASE: 'uniwa'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: '123'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '123'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - database:/var/lib/mysql

  datascience-notebook:
      image: jupyter/datascience-notebook
      user: root
      #network_mode: "host" 
      restart: always       
      environment:
        JUPYTER_ENABLE_LAB: 'yes'
      volumes:
        - notebook:/home/jovyan/work
      ports:
        - 8888:8888
      container_name: jupyter_notebook
      
  adm:
      image: adminer
      restart: always
      environment:
        ADMINER_DEFAULT_SERVER: db
      ports:
        - 8080:8080
      
# Names our volume
volumes:
  database:
  notebook:
